### ISSUE TITLE
Better error page

### ISSUE THREAD

**Issue by tteltrab** [clsavino/react-shift-scheduler#41]
If there's an error with registering the user, you probably shouldn't show them JSON. I'd suggest a splash page with a message like "We're sorry, a user with that name is already registered. Please pick a different username." with a link to your registration page.
![image](https://cloud.githubusercontent.com/assets/1487463/22172332/c7014040-df71-11e6-8bb2-7cd859e0f1f2.png)

**Comment by amr08** [comment]
Styled error page
